//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuleymaniyeCalendar.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SuleymaniyeCalendar.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle.
        /// </summary>
        internal static string Aci {
            get {
                return ResourceManager.GetString("Aci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People who are submissive to God and stand up to all difficulties for His cause are named “Muslim”. Another pertinent characteristic of those who are “Muslim” is that they apply the commandments of God into their lives without any additions to it from their own desires. “Who speaks in a finer way than the one who invokes God, does righteous deeds and says: ‘I am of those who submit themselves to God (i.e. a Muslim)’?” (Fussilat 41:33)
        ///This application is designed to provide safe and fast access to prayer a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AciklamaBas {
            get {
                return ResourceManager.GetString("AciklamaBas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prayer Times From The Equator To The Poles.
        /// </summary>
        internal static string AciklamaLinkText {
            get {
                return ResourceManager.GetString("AciklamaLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.islamandquran.org/research/prayer-times-from-the-equator-to-the-poles.html.
        /// </summary>
        internal static string AciklamaLinkURL {
            get {
                return ResourceManager.GetString("AciklamaLinkURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  should be read..
        /// </summary>
        internal static string AciklamaSon {
            get {
                return ResourceManager.GetString("AciklamaSon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light theme.
        /// </summary>
        internal static string AcikTema {
            get {
                return ResourceManager.GetString("AcikTema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Adres {
            get {
                return ResourceManager.GetString("Adres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maghrib.
        /// </summary>
        internal static string Aksam {
            get {
                return ResourceManager.GetString("Aksam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time remaining until the end of Maghrib: .
        /// </summary>
        internal static string Aksamincikmasnakalanvakit {
            get {
                return ResourceManager.GetString("Aksamincikmasnakalanvakit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem occurred while the alarm plays. Details.
        /// </summary>
        internal static string AlarmHatasi {
            get {
                return ResourceManager.GetString("AlarmHatasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm.
        /// </summary>
        internal static string Alarmi {
            get {
                return ResourceManager.GetString("Alarmi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while setting the alarm.
        /// </summary>
        internal static string Alarmkurarkenhataolustu {
            get {
                return ResourceManager.GetString("Alarmkurarkenhataolustu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduling alarms, please wait.
        /// </summary>
        internal static string AlarmlarPlanlaniyor {
            get {
                return ResourceManager.GetString("AlarmlarPlanlaniyor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm Ringtone.
        /// </summary>
        internal static string AlarmSound {
            get {
                return ResourceManager.GetString("AlarmSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm duration: .
        /// </summary>
        internal static string AlarmSuresi {
            get {
                return ResourceManager.GetString("AlarmSuresi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play the alarm.
        /// </summary>
        internal static string AlarmSwitch {
            get {
                return ResourceManager.GetString("AlarmSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm ringtone repeats: .
        /// </summary>
        internal static string AlarmTekrarlari {
            get {
                return ResourceManager.GetString("AlarmTekrarlari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic.
        /// </summary>
        internal static string Arabic {
            get {
                return ResourceManager.GetString("Arabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Calendar.
        /// </summary>
        internal static string AylikTakvim {
            get {
                return ResourceManager.GetString("AylikTakvim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not access the Monthly Calendar. Please check that you are connected to the internet and your location service is active!.
        /// </summary>
        internal static string AylikTakvimeErisemedi {
            get {
                return ResourceManager.GetString("AylikTakvimeErisemedi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Calendar Refreshed Successfully.
        /// </summary>
        internal static string AylikTakvimYenilendi {
            get {
                return ResourceManager.GetString("AylikTakvimYenilendi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please refresh to load monthly data.
        /// </summary>
        internal static string AylikVeriYenilemeIste {
            get {
                return ResourceManager.GetString("AylikVeriYenilemeIste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} data downloaded.
        /// </summary>
        internal static string AyVeriIndirildi {
            get {
                return ResourceManager.GetString("AyVeriIndirildi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download This Month.
        /// </summary>
        internal static string AyVeriYukle {
            get {
                return ResourceManager.GetString("AyVeriYukle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azerbaijani.
        /// </summary>
        internal static string Azerbaijani {
            get {
                return ResourceManager.GetString("Azerbaijani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 minutes before.
        /// </summary>
        internal static string BesDakikaOnceden {
            get {
                return ResourceManager.GetString("BesDakikaOnceden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications Disabled.
        /// </summary>
        internal static string BildiriDevreDisiBaslik {
            get {
                return ResourceManager.GetString("BildiriDevreDisiBaslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  prayer notification disabled..
        /// </summary>
        internal static string BildiriDevreDisiIcerik {
            get {
                return ResourceManager.GetString("BildiriDevreDisiIcerik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications Enabled.
        /// </summary>
        internal static string BildiriEtkinBaslik {
            get {
                return ResourceManager.GetString("BildiriEtkinBaslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  prayer notification enabled..
        /// </summary>
        internal static string BildiriEtkinIcerik {
            get {
                return ResourceManager.GetString("BildiriEtkinIcerik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show notification.
        /// </summary>
        internal static string BildirimGosterSwitch {
            get {
                return ResourceManager.GetString("BildirimGosterSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification permission required to schedule alarms..
        /// </summary>
        internal static string BildirimIzniGerekli {
            get {
                return ResourceManager.GetString("BildirimIzniGerekli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Permission Denied.
        /// </summary>
        internal static string BildirimIzniReddedildi {
            get {
                return ResourceManager.GetString("BildirimIzniReddedildi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This app needs notification permission to send you prayer time reminders. Please enable notifications in Settings..
        /// </summary>
        internal static string BildirimIzniAciklama {
            get {
                return ResourceManager.GetString("BildirimIzniAciklama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Settings.
        /// </summary>
        internal static string AyarlariAc {
            get {
                return ResourceManager.GetString("AyarlariAc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Iptal {
            get {
                return ResourceManager.GetString("Iptal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable sticky notifications.
        /// </summary>
        internal static string BildirimKapatma {
            get {
                return ResourceManager.GetString("BildirimKapatma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show prayer times in notification.
        /// </summary>
        internal static string BildirimNamazVakitleri {
            get {
                return ResourceManager.GetString("BildirimNamazVakitleri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: It may take half a minute to take effect.
        /// </summary>
        internal static string BildirimNamazVakitleriUyari {
            get {
                return ResourceManager.GetString("BildirimNamazVakitleriUyari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We recommend that you do not turn this setting off. If you turn it off, alarms may not ring on time. If your alarms do not ring, please check the application settings: In the &quot;Other permissions&quot; section, check that the &quot;Start in the Background&quot; option is selected. Make sure that the &quot;No Restrictions&quot; setting in the &quot;Battery saving&quot; section is on. To check these permissions now, click the button below..
        /// </summary>
        internal static string BildirimUyari {
            get {
                return ResourceManager.GetString("BildirimUyari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reminder Time: .
        /// </summary>
        internal static string BildirmeZamani {
            get {
                return ResourceManager.GetString("BildirmeZamani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a ringtone.
        /// </summary>
        internal static string Birsessecin {
            get {
                return ResourceManager.GetString("Birsessecin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        internal static string BoylamFormatsiz {
            get {
                return ResourceManager.GetString("BoylamFormatsiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        internal static string Bugun {
            get {
                return ResourceManager.GetString("Bugun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today&apos;s Prayer Times.
        /// </summary>
        internal static string BugunkuNamazVakitleri {
            get {
                return ResourceManager.GetString("BugunkuNamazVakitleri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm Clock.
        /// </summary>
        internal static string CalarSaat {
            get {
                return ResourceManager.GetString("CalarSaat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese.
        /// </summary>
        internal static string Chinese {
            get {
                return ResourceManager.GetString("Chinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your device does not support GPS.
        /// </summary>
        internal static string CihazGPSDesteklemiyor {
            get {
                return ResourceManager.GetString("CihazGPSDesteklemiyor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your device does not support compass.
        /// </summary>
        internal static string CihazPusulaDesteklemiyor {
            get {
                return ResourceManager.GetString("CihazPusulaDesteklemiyor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your device does not support vibration.
        /// </summary>
        internal static string CihazTitretmeyiDesteklemiyor {
            get {
                return ResourceManager.GetString("CihazTitretmeyiDesteklemiyor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  minutes.
        /// </summary>
        internal static string Dakika {
            get {
                return ResourceManager.GetString("Dakika", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  minutes before.
        /// </summary>
        internal static string DakikaOnceden {
            get {
                return ResourceManager.GetString("DakikaOnceden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        internal static string Deutsch {
            get {
                return ResourceManager.GetString("Deutsch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        internal static string DevreDisi {
            get {
                return ResourceManager.GetString("DevreDisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string Durdur {
            get {
                return ResourceManager.GetString("Durdur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        internal static string EnlemFormatsiz {
            get {
                return ResourceManager.GetString("EnlemFormatsiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string Etkin {
            get {
                return ResourceManager.GetString("Etkin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        internal static string EtkinlestirSwitch {
            get {
                return ResourceManager.GetString("EtkinlestirSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enables the alarm, vibration, and notification features for this prayer time.
        /// </summary>
        internal static string EtkinlestirSwitchAciklama {
            get {
                return ResourceManager.GetString("EtkinlestirSwitchAciklama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adhan.
        /// </summary>
        internal static string EzanSesi {
            get {
                return ResourceManager.GetString("EzanSesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farsi.
        /// </summary>
        internal static string Farsi {
            get {
                return ResourceManager.GetString("Farsi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining time for False Fajr (the beginning of Suhoor): .
        /// </summary>
        internal static string FecriKazibingirmesinekalanvakit {
            get {
                return ResourceManager.GetString("FecriKazibingirmesinekalanvakit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False Fajr (Sahar &amp; Suhoor time).
        /// </summary>
        internal static string FecriKazip {
            get {
                return ResourceManager.GetString("FecriKazip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fajr.
        /// </summary>
        internal static string FecriSadik {
            get {
                return ResourceManager.GetString("FecriSadik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining time for Fajr (the end of Suhoor): .
        /// </summary>
        internal static string FecriSadikakalanvakit {
            get {
                return ResourceManager.GetString("FecriSadikakalanvakit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radio Fitrat - The Voice of Fitrah.
        /// </summary>
        internal static string FitratinSesi {
            get {
                return ResourceManager.GetString("FitratinSesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fitrat TV.
        /// </summary>
        internal static string FitratTV {
            get {
                return ResourceManager.GetString("FitratTV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fitrat TV Facebook Page.
        /// </summary>
        internal static string FitratTVFacebook {
            get {
                return ResourceManager.GetString("FitratTVFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fitrat TV Twitter Page.
        /// </summary>
        internal static string FitratTVTwitter {
            get {
                return ResourceManager.GetString("FitratTVTwitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fitrat TV Youtube Channel.
        /// </summary>
        internal static string FitratTVYoutube {
            get {
                return ResourceManager.GetString("FitratTVYoutube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        internal static string French {
            get {
                return ResourceManager.GetString("French", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Settings.
        /// </summary>
        internal static string GotoSettings {
            get {
                return ResourceManager.GetString("GotoSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string Hakkinda {
            get {
                return ResourceManager.GetString("Hakkinda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Location On Map.
        /// </summary>
        internal static string HaritadaGoster {
            get {
                return ResourceManager.GetString("HaritadaGoster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem occurred while opening the map.\nDetails:.
        /// </summary>
        internal static string HaritaHatasi {
            get {
                return ResourceManager.GetString("HaritaHatasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error details:.
        /// </summary>
        internal static string Hatadetaylari {
            get {
                return ResourceManager.GetString("Hatadetaylari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renew location and prayer times every time the app is opened.
        /// </summary>
        internal static string HepKonumYenile {
            get {
                return ResourceManager.GetString("HepKonumYenile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rooster Crowing.
        /// </summary>
        internal static string HorozOtusu {
            get {
                return ResourceManager.GetString("HorozOtusu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content Loading ....
        /// </summary>
        internal static string IcerikYukleniyor {
            get {
                return ResourceManager.GetString("IcerikYukleniyor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asr.
        /// </summary>
        internal static string Ikindi {
            get {
                return ResourceManager.GetString("Ikindi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time remaining until the end of Asr: .
        /// </summary>
        internal static string Ikindinincikmasinakalanvakit {
            get {
                return ResourceManager.GetString("Ikindinincikmasinakalanvakit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining Time: .
        /// </summary>
        internal static string KalanSure {
            get {
                return ResourceManager.GetString("KalanSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Kapat {
            get {
                return ResourceManager.GetString("Kapat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Kaydet {
            get {
                return ResourceManager.GetString("Kaydet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and Close.
        /// </summary>
        internal static string KaydetVeKapat {
            get {
                return ResourceManager.GetString("KaydetVeKapat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and Apply.
        /// </summary>
        internal static string KaydetVeUygula {
            get {
                return ResourceManager.GetString("KaydetVeUygula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  times.
        /// </summary>
        internal static string Kere {
            get {
                return ResourceManager.GetString("Kere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qibla.
        /// </summary>
        internal static string Kible {
            get {
                return ResourceManager.GetString("Kible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qibla Direction.
        /// </summary>
        internal static string KibleGostergesi {
            get {
                return ResourceManager.GetString("KibleGostergesi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location information.
        /// </summary>
        internal static string KonumBilgileri {
            get {
                return ResourceManager.GetString("KonumBilgileri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem occurred trying to get location.
        /// </summary>
        internal static string KonumHatasi {
            get {
                return ResourceManager.GetString("KonumHatasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Permission to Access the Location.
        /// </summary>
        internal static string KonumIzniBaslik {
            get {
                return ResourceManager.GetString("KonumIzniBaslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For normal operation of the application, you need to give permission to access the Location!.
        /// </summary>
        internal static string KonumIzniIcerik {
            get {
                return ResourceManager.GetString("KonumIzniIcerik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location services are not enabled on the device. You have to turn on location services first!.
        /// </summary>
        internal static string KonumKapali {
            get {
                return ResourceManager.GetString("KonumKapali", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Services Off.
        /// </summary>
        internal static string KonumKapaliBaslik {
            get {
                return ResourceManager.GetString("KonumKapaliBaslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string KonumYenileButton {
            get {
                return ResourceManager.GetString("KonumYenileButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location and prayer times refreshed successfully.
        /// </summary>
        internal static string KonumYenilendi {
            get {
                return ResourceManager.GetString("KonumYenilendi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark theme.
        /// </summary>
        internal static string KoyuTema {
            get {
                return ResourceManager.GetString("KoyuTema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birds.
        /// </summary>
        internal static string KusCiviltisi {
            get {
                return ResourceManager.GetString("KusCiviltisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kyrgyz.
        /// </summary>
        internal static string Kyrgyz {
            get {
                return ResourceManager.GetString("Kyrgyz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while retrieving the prayer times from the internet..
        /// </summary>
        internal static string NamazVaktiAlmaHatasi {
            get {
                return ResourceManager.GetString("NamazVaktiAlmaHatasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dhuhr.
        /// </summary>
        internal static string Ogle {
            get {
                return ResourceManager.GetString("Ogle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time remaining until the end of Dhuhr: .
        /// </summary>
        internal static string Oglenincikmasinakalanvakit {
            get {
                return ResourceManager.GetString("Oglenincikmasinakalanvakit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining time for Dhuhr: .
        /// </summary>
        internal static string Ogleningirmesinekalanvakit {
            get {
                return ResourceManager.GetString("Ogleningirmesinekalanvakit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15 minutes before.
        /// </summary>
        internal static string OnBesDakikaOnceden {
            get {
                return ResourceManager.GetString("OnBesDakikaOnceden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load prayer times for scheduling.
        /// </summary>
        internal static string OtuzGunHatirlaticiHatasi {
            get {
                return ResourceManager.GetString("OtuzGunHatirlaticiHatasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prayer reminders scheduled for 30 days.
        /// </summary>
        internal static string OtuzGunHatirlaticiPlanlandi {
            get {
                return ResourceManager.GetString("OtuzGunHatirlaticiPlanlandi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        internal static string Oynat {
            get {
                return ResourceManager.GetString("Oynat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suleymaniye Calendar.
        /// </summary>
        internal static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        internal static string Paylas {
            get {
                return ResourceManager.GetString("Paylas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radio.
        /// </summary>
        internal static string Radyo {
            get {
                return ResourceManager.GetString("Radyo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play or pause radio.
        /// </summary>
        internal static string RadyoCal {
            get {
                return ResourceManager.GetString("RadyoCal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radio Fitrat.
        /// </summary>
        internal static string RadyoFitrat {
            get {
                return ResourceManager.GetString("RadyoFitrat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radio Fitrat Facebook Page.
        /// </summary>
        internal static string RadyoFitratFaceBook {
            get {
                return ResourceManager.GetString("RadyoFitratFaceBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radio Fitrat Instagram Page.
        /// </summary>
        internal static string RadyoFitratInstagram {
            get {
                return ResourceManager.GetString("RadyoFitratInstagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radio Fitrat Twitter Page.
        /// </summary>
        internal static string RadyoFitratTwitter {
            get {
                return ResourceManager.GetString("RadyoFitratTwitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet connection required to play the radio, please check your Internet connection. Alternatively, you can listen to the radio by clicking the &apos;Web Site&apos; link..
        /// </summary>
        internal static string RadyoIcinInternet {
            get {
                return ResourceManager.GetString("RadyoIcinInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian.
        /// </summary>
        internal static string Russian {
            get {
                return ResourceManager.GetString("Russian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of Fajr.
        /// </summary>
        internal static string SabahSonu {
            get {
                return ResourceManager.GetString("SabahSonu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time remaining until the end of Fajr: .
        /// </summary>
        internal static string SabahSonunakalanvakit {
            get {
                return ResourceManager.GetString("SabahSonunakalanvakit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string Sehir {
            get {
                return ResourceManager.GetString("Sehir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the alarm ringtone for this prayer time.
        /// </summary>
        internal static string SesSecAciklama {
            get {
                return ResourceManager.GetString("SesSecAciklama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound Test.
        /// </summary>
        internal static string SesTesti {
            get {
                return ResourceManager.GetString("SesTesti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System theme.
        /// </summary>
        internal static string SistemTemasi {
            get {
                return ResourceManager.GetString("SistemTemasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We Encountered a Problem.
        /// </summary>
        internal static string SorunCikti {
            get {
                return ResourceManager.GetString("SorunCikti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Social Media Links.
        /// </summary>
        internal static string SosyalMedyaBaglantisi {
            get {
                return ResourceManager.GetString("SosyalMedyaBaglantisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suleymaniye Foundation.
        /// </summary>
        internal static string SuleymaniyeVakfi {
            get {
                return ResourceManager.GetString("SuleymaniyeVakfi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suleymaniye Foundation Facebook Page.
        /// </summary>
        internal static string SuleymaniyeVakfiFacebook {
            get {
                return ResourceManager.GetString("SuleymaniyeVakfiFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suleymaniye Foundation Instagram Page.
        /// </summary>
        internal static string SuleymaniyeVakfiInstagram {
            get {
                return ResourceManager.GetString("SuleymaniyeVakfiInstagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suleymaniye Calendar.
        /// </summary>
        internal static string SuleymaniyeVakfiTakvimi {
            get {
                return ResourceManager.GetString("SuleymaniyeVakfiTakvimi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suleymaniye Foundation Twitter Page.
        /// </summary>
        internal static string SuleymaniyeVakfiTwitter {
            get {
                return ResourceManager.GetString("SuleymaniyeVakfiTwitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        internal static string Takvim {
            get {
                return ResourceManager.GetString("Takvim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To renew the prayer times, you need to be connected to the internet. Turn on WiFi or Mobile data and click &apos;REFRESH&apos;..
        /// </summary>
        internal static string TakvimIcinInternet {
            get {
                return ResourceManager.GetString("TakvimIcinInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet Connection Required.
        /// </summary>
        internal static string TakvimIcinInternetBaslik {
            get {
                return ResourceManager.GetString("TakvimIcinInternetBaslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Tamam {
            get {
                return ResourceManager.GetString("Tamam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Tarih {
            get {
                return ResourceManager.GetString("Tarih", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop the Test.
        /// </summary>
        internal static string TestiDurdur {
            get {
                return ResourceManager.GetString("TestiDurdur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your device does not support vibration..
        /// </summary>
        internal static string TitremeyiDesteklemiyor {
            get {
                return ResourceManager.GetString("TitremeyiDesteklemiyor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vibrate.
        /// </summary>
        internal static string TitresimSwitch {
            get {
                return ResourceManager.GetString("TitresimSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkish.
        /// </summary>
        internal static string Turkish {
            get {
                return ResourceManager.GetString("Turkish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uyghur.
        /// </summary>
        internal static string Uyghur {
            get {
                return ResourceManager.GetString("Uyghur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Settings.
        /// </summary>
        internal static string UygulamaAyarlari {
            get {
                return ResourceManager.GetString("UygulamaAyarlari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App language.
        /// </summary>
        internal static string UygulamaDili {
            get {
                return ResourceManager.GetString("UygulamaDili", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the app language.
        /// </summary>
        internal static string UygulamaDiliniSecin {
            get {
                return ResourceManager.GetString("UygulamaDiliniSecin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App theme.
        /// </summary>
        internal static string UygulamaTema {
            get {
                return ResourceManager.GetString("UygulamaTema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the app theme.
        /// </summary>
        internal static string UygulamaTemasiniSecin {
            get {
                return ResourceManager.GetString("UygulamaTemasiniSecin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uzbek.
        /// </summary>
        internal static string Uzbek {
            get {
                return ResourceManager.GetString("Uzbek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time: .
        /// </summary>
        internal static string Vakti {
            get {
                return ResourceManager.GetString("Vakti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Reminder.
        /// </summary>
        internal static string VaktiHatirlatmasi {
            get {
                return ResourceManager.GetString("VaktiHatirlatmasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to version.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Web Site.
        /// </summary>
        internal static string WebSayfa {
            get {
                return ResourceManager.GetString("WebSayfa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isha.
        /// </summary>
        internal static string Yatsi {
            get {
                return ResourceManager.GetString("Yatsi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time remaining until the end of Isha: .
        /// </summary>
        internal static string Yatsinincikmasinakalanvakit {
            get {
                return ResourceManager.GetString("Yatsinincikmasinakalanvakit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time elapsed since the end of Isha: .
        /// </summary>
        internal static string Yatsininciktigindangecenvakit {
            get {
                return ResourceManager.GetString("Yatsininciktigindangecenvakit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End of Isha.
        /// </summary>
        internal static string YatsiSonu {
            get {
                return ResourceManager.GetString("YatsiSonu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Program Schedule.
        /// </summary>
        internal static string YayinAkisi {
            get {
                return ResourceManager.GetString("YayinAkisi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Size: .
        /// </summary>
        internal static string YaziBoyutu {
            get {
                return ResourceManager.GetString("YaziBoyutu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string Yenile {
            get {
                return ResourceManager.GetString("Yenile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refreshing.
        /// </summary>
        internal static string Yenileniyor {
            get {
                return ResourceManager.GetString("Yenileniyor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altitude.
        /// </summary>
        internal static string YukseklikFormatsiz {
            get {
                return ResourceManager.GetString("YukseklikFormatsiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On time.
        /// </summary>
        internal static string Zamaninda {
            get {
                return ResourceManager.GetString("Zamaninda", resourceCulture);
            }
        }
    }
}
